// * Main.c file generated by New Project wizard
//  *
//  * Created:   Fri Nov 11 2022
//  * Processor: PIC18F24K22
//  * Compiler:  MPLAB XC8
//  */
#include<avr/io.h>
#define F_CPU 1000000UL
#include<util/delay.h>
#define MrLCDsCrib PORTB   
#define DataDir_MrLCDsCrib DDRB
#define MrLCDControl PORTD
#define DataDir_MrLCDControl  DDRD
#define LightSwitch 5
#define ReadWrite 7
#define BiPolarMood 2

void check_if_MrLCD_isbusy(void);
void peek_a_boo(void);
void send_a_command(unsigned char command);
void send_a_character(unsigned char character);


int main(void)
 {
    DataDir_MrLCDControl |= 1<<LightSwitch | 1<<ReadWrite  | 1<<BiPolarMood;
    
   _delay_ms(15);
   send_a_command(0x01);   //clearr screen  0x01= 00000001
    _delay_ms(2);
    send_a_command(0x38);
    _delay_us(50);
    send_a_command(0b00001110);
    _delay_us(50);
    send_a_character(0x4E);  //Display A
    send_a_character(0x65);
    send_a_character(0x77);
    send_a_character(0x62);
    send_a_character(0x69);
    send_a_character(0x65);
    send_a_character(0x48);
    send_a_character(0x61);
    send_a_character(0x63);
    send_a_character(0x6B);
   while (1)
   {
      }
 }
 void check_if_MrLCD_isbusy(){
    DataDir_MrLCDsCrib = 0;
      MrLCDControl |=1<<ReadWrite;
      MrLCDControl &=~(1<<BiPolarMood);
    while(MrLCDsCrib >= 0x80){
       peek_a_boo();
       }
     DataDir_MrLCDsCrib = 0xFF; //0xFF means 0b11111111
    }
 void peek_a_boo(void){
     MrLCDControl |=1<<LightSwitch;
    asm volatile("nop");
    asm volatile("nop");
     MrLCDControl &=~(1<<LightSwitch);
    
    }
 void send_a_command(unsigned char command){
    check_if_MrLCD_isbusy();
    MrLCDsCrib = command;
    MrLCDControl &= ~(1<<ReadWrite | 1<<BiPolarMood);
    peek_a_boo();
    MrLCDsCrib = 0;
    
    }
 void send_a_character(unsigned char character){
    check_if_MrLCD_isbusy();
     MrLCDsCrib = character;
    MrLCDControl &= ~(1<<ReadWrite );
    MrLCDControl |= 1<<BiPolarMood;
    
    peek_a_boo();
    MrLCDsCrib = 0;
    }